// ==WindhawkMod==
// @id              folder-thumbnail-style-switcher
// @name            Folder Thumbnail Style Switcher
// @description     Switch Explorer folder thumbnails between Windows 7, Windows 10, and Windows 11 styles.
// @version         2.0
// @author          QCQ171-C
// @github          https://github.com/QCQ171-C
// @include         explorer.exe
// @architecture    x86-64
// @compilerOptions -lgdi32 -lmsimg32 -luser32 -lshlwapi -lole32 -lcomctl32 -lshell32 -lwindowscodecs -fms-extensions
// ==/WindhawkMod==

// ==WindhawkModReadme==
/*
# Folder Thumbnail Style Switcher
Tested on Windows 10 22H2, Windows 11 22H2, 23H2, 24H2, 25H2 with Windhawk 1.7.1

It may support Windows 10 older version, try by yourself

## 📌Preparation
Please prepare icon group 5, 6 in imageres.dll and Bitmap 311 in shell32.dll from the respective Windows to match the folder icons and the shadow.
And you need to clean the thumbnail cache after changing a style!

## 🎞Gallery
| Picture | Style |
|:---:|:---:|
|![7 style](https://raw.githubusercontent.com/QCQ171-C/mods-collection/refs/heads/main/Gallery/folder-thumbnail-tweaker/7.PNG)|Original 7 style|
|![10 style](https://raw.githubusercontent.com/QCQ171-C/mods-collection/refs/heads/main/Gallery/folder-thumbnail-tweaker/10.PNG)|Original 10 style|
|![11 style](https://raw.githubusercontent.com/QCQ171-C/mods-collection/refs/heads/main/Gallery/folder-thumbnail-tweaker/11.png)|Original 11 style|
|![7 style on 10](https://raw.githubusercontent.com/QCQ171-C/mods-collection/refs/heads/main/Gallery/folder-thumbnail-tweaker/10-7.PNG)|7 style on Windows 10|
|![11 style on 10](https://raw.githubusercontent.com/QCQ171-C/mods-collection/refs/heads/main/Gallery/folder-thumbnail-tweaker/10-11.png)|11 style on Windows 10|
|![7 style on 11](https://raw.githubusercontent.com/QCQ171-C/mods-collection/refs/heads/main/Gallery/folder-thumbnail-tweaker/11-7.PNG)|7 style on Windows 11|
|![10 style on 11](https://raw.githubusercontent.com/QCQ171-C/mods-collection/refs/heads/main/Gallery/folder-thumbnail-tweaker/11-10.png)|10 style on 11|

What's the difference🤨? The position and the size of the thumbnails and the shadow are different.

## ⚠️Notes
**Note 1:**
**This mod only include explorer.exe as it's the main process that handle thumbnail drawing. However, thumbnails in other processes remain the old ones (e.g. File choosing dialogs).You can change the include to:**
**`// @include *`, but it may cause problems.**

Note 2:
Windows 10 has an issue, or rather a bug, when drawing thumbnails. 
Folder icons are split into two parts - the front and the back - and stored as icons 5 and 6 in imageres.dll, as well as the "multiple folder icon" at icon number 162.
Normally, the front half of the folder should have the same logic for whether to draw or not as the back half.
However, the engineers seem to have taken the shortcut of always drawing the front half, which leads to errors in the thumbnails of such folders after replacing the icons.
This mod attempts to fix this issue. `s_DrawIcon` hook is for this.

Note 3:
Windows 10 uses GDI to draw the thumbnails, while Windows 11 uses D2D/WIC. The latter one has higher resolution.
This mod try to replicate that too.

Note 4:
I try my best to closely replicates the thumbnail drawing logic, including the shadow. Feel free to raise an issue.

## 🔵Credit
*win7-folder-thumbnail-skewing credited to [Leymonaide](https://github.com/Leymonaide "Leymonaide")*

*This code is generated by AI*
*/
// ==/WindhawkModReadme==

// ==WindhawkModSettings==
/*
- thumbnailStyle: win7
  $name: Folder thumbnail style
  $description: Selecting the style that you like.
  $options:
  - win7: Windows 7 Skewing Thumbnail
  - win10: Windows 10 Skewing Thumbnail
  - win11: Windows 11 Flat Thumbnail
*/
// ==/WindhawkModSettings==

// Compatible with Windhawk 1.6.1 and before
#undef WINAPI
#define WINAPI __attribute__((stdcall))
#include <windhawk_utils.h>
#undef WINAPI
#define WINAPI __stdcall

#include <windows.h>
#include <commctrl.h>
#include <shlobj.h>
#include <shobjidl.h>
#include <thumbcache.h>
#include <wincodec.h>
#include <initguid.h>
#include <wrl/client.h>
#include <wil/resource.h>
#include <wil/result_macros.h>
#include <algorithm>
#include <vector>

using Microsoft::WRL::ComPtr;

DEFINE_GUID(IID_IShellItemImageFactoryPriv,
    0x8A322201, 0x0A87, 0x46C1, 0x9C, 0x77, 0x76, 0x20, 0xE0, 0xCC, 0x5B, 0xBC);

DEFINE_GUID(IID_IImageList,
    0x46EB5926, 0x582E, 0x4017, 0x9F, 0xDF, 0xE8, 0x99, 0x8D, 0xAA, 0x09, 0x50);

enum WTS_STREAMTYPE { WTSST_UNKNOWN = 0, WTSST_JPEG = 1, WTSST_BMP = 2, WTSST_PNG = 3 };
enum WTS_THUMBNAILTYPE { WTSTT_IMAGE = 0, WTSTT_ICON = 1 };

MIDL_INTERFACE("8a322201-0a87-46c1-9c77-7620e0cc5bbc")
IShellItemImageFactoryPriv : IShellItemImageFactory {
    STDMETHOD(GetSharedBitmap)(SIZE, SIIGBF, ISharedBitmap**) PURE;
    STDMETHOD(GetAdornedBitmap)(SIZE, SIIGBF, ISharedBitmap**) PURE;
    STDMETHOD(GetImageStream)(SIZE, SIIGBF, WTS_STREAMTYPE*, WTS_THUMBNAILTYPE*, WTS_CACHEFLAGS*, SIZE*, REFIID, void**) PURE;
    STDMETHOD(GetImageStreamForRequestedIconSize)(SIZE, SIZE, SIIGBF, UINT64, WTS_STREAMTYPE*, WTS_THUMBNAILTYPE*, WTS_CACHEFLAGS*, SIZE*, REFIID, void**) PURE;
};

enum FolderThumbnailStyle {
    Win7,
    Win10,
    Win11,
};

enum class BitmapFlagOrder {
    Win7,
    Win10,
    Win11,
};

using Extract_t = HRESULT(__fastcall*)(void* pThis, HBITMAP* bitmap);
using GetThumbnails_t = HRESULT(__fastcall*)(void* pThis, BYTE count, void* dpa);
using SkewThumbnail_t = HRESULT(__fastcall*)(void* self, UINT index, IShellItem* item, HDC hdc, SIZE target);
using DrawIcon_t = HRESULT(__fastcall*)(int stockIconId, HDC hdc, SIZE target, int flags);

static Extract_t Extract_orig;
static GetThumbnails_t _GetThumbnails_orig;
static SkewThumbnail_t _SkewThumbnail_orig;
static DrawIcon_t s_DrawIcon_orig;
// Coordinates the Win10 front-shell suppression between _SkewThumbnail_hook
// and s_DrawIcon_hook. This assumes Explorer calls both hooks on the same
// thread while composing one folder thumbnail.
static thread_local bool g_drawWin10FrontShellForCurrentThumbnail;
static FolderThumbnailStyle g_hostStyle;
static FolderThumbnailStyle g_targetStyle;

static constexpr SIZE kCanvasSize = { 256, 256 };
static constexpr SIZE kSkewCanvasSize = { 512, 512 };
static constexpr SIZE kWin7PreviewSize = { 256, 256 };
static constexpr SIZE kWin10PreviewSize = { 254, 254 };
static constexpr SIZE kWin11ContentSize = { 208, 136 };
static constexpr SIIGBF kThumbnailFlags = static_cast<SIIGBF>(0x50008);
static constexpr SIIGBF kIconFlags = static_cast<SIIGBF>(0x50004);
static constexpr SIIGBF kCompatFlags = static_cast<SIIGBF>(0x20);

struct SkewInfo {
    SIZE size;
    POINT primary[3];
    POINT secondary[3];
};

static constexpr SkewInfo kWin7SkewInfo = {
    { 512, 512 },
    { { 50, 36 }, { 394, 116 }, { 50, 402 } },
    { { 50, 36 }, { 266, 140 }, { 50, 402 } },
};

class ScopedScreenDC {
public:
    ScopedScreenDC() : dc_(GetDC(nullptr)) {}
    ~ScopedScreenDC() {
        if (dc_) {
            ReleaseDC(nullptr, dc_);
        }
    }
    ScopedScreenDC(const ScopedScreenDC&) = delete;
    ScopedScreenDC& operator=(const ScopedScreenDC&) = delete;
    HDC get() const { return dc_; }
    explicit operator bool() const { return dc_ != nullptr; }

private:
    HDC dc_;
};

template <typename T>
static T LocalMin(T a, T b) {
    return a < b ? a : b;
}

template <typename T>
static T LocalMax(T a, T b) {
    return a > b ? a : b;
}

static HRESULT Create32BitHBITMAP(HDC hdc, const SIZE& size, void** bits, HBITMAP* bitmap) {
    *bits = nullptr;
    *bitmap = nullptr;

    BITMAPINFO bmi = {};
    bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
    bmi.bmiHeader.biWidth = size.cx;
    bmi.bmiHeader.biHeight = -size.cy;
    bmi.bmiHeader.biPlanes = 1;
    bmi.bmiHeader.biBitCount = 32;
    bmi.bmiHeader.biCompression = BI_RGB;

    HDC actualDc = hdc ? hdc : GetDC(nullptr);
    if (!actualDc) {
        return HRESULT_FROM_WIN32(GetLastError());
    }

    *bitmap = CreateDIBSection(actualDc, &bmi, DIB_RGB_COLORS, bits, nullptr, 0);
    DWORD error = GetLastError();
    if (!hdc) {
        ReleaseDC(nullptr, actualDc);
    }

    if (!*bitmap) {
        return error ? HRESULT_FROM_WIN32(error) : E_OUTOFMEMORY;
    }

    return S_OK;
}

static HRESULT CopyBitmap(HBITMAP source, HBITMAP* copy) {
    *copy = nullptr;

    BITMAP bm = {};
    RETURN_LAST_ERROR_IF(!GetObjectW(source, sizeof(bm), &bm));

    ScopedScreenDC screenDc;
    RETURN_LAST_ERROR_IF_NULL(screenDc.get());

    wil::unique_hdc sourceDc(CreateCompatibleDC(screenDc.get()));
    wil::unique_hdc copyDc(CreateCompatibleDC(screenDc.get()));
    RETURN_HR_IF_NULL(E_OUTOFMEMORY, sourceDc);
    RETURN_HR_IF_NULL(E_OUTOFMEMORY, copyDc);

    SIZE size = { bm.bmWidth, bm.bmHeight };
    void* bits = nullptr;
    HBITMAP copyBitmap = nullptr;
    RETURN_IF_FAILED(Create32BitHBITMAP(screenDc.get(), size, &bits, &copyBitmap));
    wil::unique_hbitmap copyGuard(copyBitmap);

    wil::unique_select_object sourceSel(SelectObject(sourceDc.get(), source));
    wil::unique_select_object copySel(SelectObject(copyDc.get(), copyBitmap));
    RETURN_LAST_ERROR_IF(!BitBlt(copyDc.get(), 0, 0, bm.bmWidth, bm.bmHeight, sourceDc.get(), 0, 0, SRCCOPY));

    *copy = copyGuard.release();
    return S_OK;
}

static void SetAlpha(RGBQUAD* pixels, int width, int height, BYTE alpha) {
    for (int i = 0; i < width * height; ++i) {
        pixels[i].rgbReserved = alpha;
    }
}

static void ScalePoints(POINT points[3], SIZE base, SIZE target) {
    for (int i = 0; i < 3; ++i) {
        points[i].x = MulDiv(points[i].x, target.cx, base.cx);
        points[i].y = MulDiv(points[i].y, target.cy, base.cy);
    }
}

static HRESULT ScaleBitmapUsingWIC(HBITMAP source, const SIZE& targetSize, HBITMAP* scaled) {
    *scaled = nullptr;

    ScopedScreenDC screenDc;
    RETURN_LAST_ERROR_IF_NULL(screenDc.get());

    void* bits = nullptr;
    HBITMAP scaledBitmap = nullptr;
    RETURN_IF_FAILED(Create32BitHBITMAP(screenDc.get(), targetSize, &bits, &scaledBitmap));
    wil::unique_hbitmap scaledGuard(scaledBitmap);

    ComPtr<IWICImagingFactory> factory;
    RETURN_IF_FAILED(CoCreateInstance(CLSID_WICImagingFactory, nullptr, CLSCTX_INPROC_SERVER, IID_PPV_ARGS(&factory)));

    ComPtr<IWICBitmap> wicSource;
    RETURN_IF_FAILED(factory->CreateBitmapFromHBITMAP(source, nullptr, WICBitmapUseAlpha, &wicSource));

    ComPtr<IWICBitmapScaler> scaler;
    RETURN_IF_FAILED(factory->CreateBitmapScaler(&scaler));
    RETURN_IF_FAILED(scaler->Initialize(wicSource.Get(), targetSize.cx, targetSize.cy, WICBitmapInterpolationModeFant));

    UINT stride = targetSize.cx * sizeof(RGBQUAD);
    UINT bufferSize = stride * targetSize.cy;
    RETURN_IF_FAILED(scaler->CopyPixels(nullptr, stride, bufferSize, static_cast<BYTE*>(bits)));

    *scaled = scaledGuard.release();
    return S_OK;
}

static void CompositePBGRAOver(RGBQUAD* dest, const RGBQUAD& src) {
    BYTE srcA = src.rgbReserved;
    if (!srcA) {
        return;
    }

    BYTE invA = 255 - srcA;
    dest->rgbBlue = static_cast<BYTE>(src.rgbBlue + (dest->rgbBlue * invA + 127) / 255);
    dest->rgbGreen = static_cast<BYTE>(src.rgbGreen + (dest->rgbGreen * invA + 127) / 255);
    dest->rgbRed = static_cast<BYTE>(src.rgbRed + (dest->rgbRed * invA + 127) / 255);
    dest->rgbReserved = static_cast<BYTE>(srcA + (dest->rgbReserved * invA + 127) / 255);
}

static HRESULT DrawBitmapWithWIC(HBITMAP source,
                                 RGBQUAD* destBits,
                                 const SIZE& destSize,
                                 int destX,
                                 int destY,
                                 int destW,
                                 int destH) {
    RETURN_HR_IF(E_INVALIDARG, !source || !destBits || destW <= 0 || destH <= 0);

    ComPtr<IWICImagingFactory> factory;
    RETURN_IF_FAILED(CoCreateInstance(CLSID_WICImagingFactory, nullptr, CLSCTX_INPROC_SERVER, IID_PPV_ARGS(&factory)));

    ComPtr<IWICBitmap> sourceBitmap;
    RETURN_IF_FAILED(factory->CreateBitmapFromHBITMAP(source, nullptr, WICBitmapUsePremultipliedAlpha, &sourceBitmap));

    ComPtr<IWICBitmapScaler> scaler;
    RETURN_IF_FAILED(factory->CreateBitmapScaler(&scaler));
    RETURN_IF_FAILED(scaler->Initialize(sourceBitmap.Get(), destW, destH, WICBitmapInterpolationModeCubic));

    ComPtr<IWICFormatConverter> converter;
    RETURN_IF_FAILED(factory->CreateFormatConverter(&converter));
    RETURN_IF_FAILED(converter->Initialize(
        scaler.Get(), GUID_WICPixelFormat32bppPBGRA, WICBitmapDitherTypeNone, nullptr, 0.0, WICBitmapPaletteTypeCustom));

    int visibleLeft = LocalMax(destX, 0);
    int visibleTop = LocalMax(destY, 0);
    int visibleRight = LocalMin(destX + destW, static_cast<int>(destSize.cx));
    int visibleBottom = LocalMin(destY + destH, static_cast<int>(destSize.cy));
    if (visibleRight <= visibleLeft || visibleBottom <= visibleTop) {
        return S_OK;
    }

    WICRect copyRect = {
        visibleLeft - destX,
        visibleTop - destY,
        visibleRight - visibleLeft,
        visibleBottom - visibleTop,
    };

    UINT stride = copyRect.Width * sizeof(RGBQUAD);
    UINT bufferSize = stride * copyRect.Height;
    wil::unique_cotaskmem_ptr<RGBQUAD> buffer(static_cast<RGBQUAD*>(CoTaskMemAlloc(bufferSize)));
    RETURN_HR_IF_NULL(E_OUTOFMEMORY, buffer);
    RETURN_IF_FAILED(converter->CopyPixels(&copyRect, stride, bufferSize, reinterpret_cast<BYTE*>(buffer.get())));

    for (int y = 0; y < copyRect.Height; ++y) {
        RGBQUAD* sourceRow = buffer.get() + y * copyRect.Width;
        RGBQUAD* destRow = destBits + (visibleTop + y) * destSize.cx + visibleLeft;
        for (int x = 0; x < copyRect.Width; ++x) {
            CompositePBGRAOver(&destRow[x], sourceRow[x]);
        }
    }

    return S_OK;
}

static bool LooksLikePhotoBitmap(HBITMAP bitmap) {
    BITMAP bm = {};
    if (!GetObjectW(bitmap, sizeof(bm), &bm)) {
        return false;
    }

    int width = static_cast<int>(bm.bmWidth);
    int height = static_cast<int>(bm.bmHeight);
    int delta = abs(width - height);
    return (width >= 128 || height >= 128) && delta > LocalMax(12, LocalMin(width, height) / 12);
}

static HRESULT DrawStockIconLayer(HDC destDc, SHSTOCKICONID stockId, const SIZE& canvas, int flags = 0) {
    if (canvas.cx > kCanvasSize.cx || canvas.cy > kCanvasSize.cy) {
        ScopedScreenDC screenDc;
        RETURN_LAST_ERROR_IF_NULL(screenDc.get());

        wil::unique_hdc tempDc(CreateCompatibleDC(screenDc.get()));
        RETURN_HR_IF_NULL(E_OUTOFMEMORY, tempDc);

        void* tempBits = nullptr;
        HBITMAP tempBitmap = nullptr;
        RETURN_IF_FAILED(Create32BitHBITMAP(screenDc.get(), kCanvasSize, &tempBits, &tempBitmap));
        wil::unique_hbitmap tempGuard(tempBitmap);
        wil::unique_select_object tempSel(SelectObject(tempDc.get(), tempBitmap));
        ZeroMemory(tempBits, kCanvasSize.cx * kCanvasSize.cy * sizeof(RGBQUAD));

        RETURN_IF_FAILED(DrawStockIconLayer(tempDc.get(), stockId, kCanvasSize, flags));

        HBITMAP scaledBitmap = nullptr;
        RETURN_IF_FAILED(ScaleBitmapUsingWIC(tempBitmap, canvas, &scaledBitmap));
        wil::unique_hbitmap scaledGuard(scaledBitmap);

        wil::unique_hdc scaledDc(CreateCompatibleDC(screenDc.get()));
        RETURN_HR_IF_NULL(E_OUTOFMEMORY, scaledDc);
        wil::unique_select_object scaledSel(SelectObject(scaledDc.get(), scaledBitmap));

        BLENDFUNCTION blend = { AC_SRC_OVER, 0, 255, AC_SRC_ALPHA };
        RETURN_LAST_ERROR_IF(!GdiAlphaBlend(destDc, 0, 0, canvas.cx, canvas.cy, scaledDc.get(), 0, 0, canvas.cx, canvas.cy, blend));
        return S_OK;
    }

    SHSTOCKICONINFO sii = {};
    sii.cbSize = sizeof(sii);
    RETURN_IF_FAILED(SHGetStockIconInfo(stockId, SHGSI_SYSICONINDEX, &sii));

    void* imageListRaw = nullptr;
    RETURN_IF_FAILED(SHGetImageList(SHIL_JUMBO, IID_IImageList, &imageListRaw));

    IUnknown* imageListUnknown = static_cast<IUnknown*>(imageListRaw);
    HIMAGELIST imageList = reinterpret_cast<HIMAGELIST>(imageListRaw);
    IMAGELISTDRAWPARAMS drawParams = {};
    drawParams.cbSize = sizeof(drawParams);
    drawParams.himl = imageList;
    drawParams.i = sii.iSysImageIndex & 0x00FFFFFF;
    drawParams.hdcDst = destDc;
    drawParams.cx = canvas.cx;
    drawParams.cy = canvas.cy;
    drawParams.rgbBk = 0xFF000000;
    drawParams.rgbFg = CLR_NONE;
    drawParams.fStyle = flags ? ILD_TRANSPARENT : ILD_NORMAL;

    BOOL drawn = ImageList_DrawIndirect(&drawParams);
    imageListUnknown->Release();
    return drawn ? S_OK : HRESULT_FROM_WIN32(GetLastError());
}

static HRESULT GetShellItemBitmap(IShellItem* item, const SIZE& size, SIIGBF thumbnailFlags, SIIGBF iconFlags, SIIGBF fallbackFlags, BitmapFlagOrder flagOrder, bool use128ForIcons, HBITMAP* bitmap, bool* imageThumbnail) {
    *bitmap = nullptr;
    *imageThumbnail = false;

    ComPtr<IShellItemImageFactoryPriv> privateFactory;
    if (SUCCEEDED(item->QueryInterface(IID_IShellItemImageFactoryPriv, reinterpret_cast<void**>(privateFactory.GetAddressOf())))) {
        ComPtr<IStream> imageStream;
        WTS_STREAMTYPE streamType = WTSST_UNKNOWN;
        WTS_THUMBNAILTYPE thumbnailType = WTSTT_ICON;
        WTS_CACHEFLAGS cacheFlags = static_cast<WTS_CACHEFLAGS>(0);
        SIZE actualSize = {};

        if (SUCCEEDED(privateFactory->GetImageStream(size, thumbnailFlags, &streamType, &thumbnailType, &cacheFlags, &actualSize, __uuidof(IStream), reinterpret_cast<void**>(imageStream.GetAddressOf())))) {
            *imageThumbnail = thumbnailType == WTSTT_IMAGE;
        }

        const SIZE bitmapSize = (!*imageThumbnail && use128ForIcons) ? SIZE{ 128, 128 } : size;
        const SIIGBF preferredFlags = *imageThumbnail ? thumbnailFlags : iconFlags;
        SIIGBF flags[3] = {};
        if (flagOrder == BitmapFlagOrder::Win7) {
            flags[0] = thumbnailFlags;
            flags[1] = fallbackFlags;
            flags[2] = iconFlags;
        } else if (flagOrder == BitmapFlagOrder::Win10) {
            flags[0] = fallbackFlags;
            flags[1] = thumbnailFlags;
            flags[2] = iconFlags;
        } else {
            flags[0] = preferredFlags;
            flags[1] = thumbnailFlags;
            flags[2] = fallbackFlags;
        }

        for (int i = 0; i < 3; ++i) {
            ComPtr<ISharedBitmap> sharedBitmap;
            if (SUCCEEDED(privateFactory->GetSharedBitmap(bitmapSize, flags[i], &sharedBitmap)) && sharedBitmap) {
                HBITMAP shared = nullptr;
                RETURN_IF_FAILED(sharedBitmap->GetSharedBitmap(&shared));
                if (shared && SUCCEEDED(CopyBitmap(shared, bitmap)) && *bitmap) {
                    return S_OK;
                }
            }
        }
    }

    ComPtr<IShellItemImageFactory> factory;
    RETURN_IF_FAILED(item->QueryInterface(IID_PPV_ARGS(&factory)));

    HRESULT hr = factory->GetImage(size, thumbnailFlags, bitmap);
    if (FAILED(hr) || !*bitmap) {
        hr = factory->GetImage(size, fallbackFlags, bitmap);
    }

    return hr;
}

struct FakeCDPA {
    HDPA hdpa;
};

static int CALLBACK ReleaseShellItemDpaCallback(void* item, void*) {
    if (item) {
        static_cast<IUnknown*>(item)->Release();
    }
    return 1;
}

struct ChildBitmap {
    HBITMAP bitmap = nullptr;
    bool imageThumbnail = false;
    bool photoLike = false;
    int area = 0;
    int originalIndex = 0;
};

static int GetFolderChildBitmaps(void* folderThis, FolderThumbnailStyle style, ChildBitmap outBitmaps[2]) {
    outBitmaps[0] = {};
    outBitmaps[1] = {};

    HDPA hdpa = DPA_Create(2);
    if (!hdpa) {
        return 0;
    }

    FakeCDPA dpa = { hdpa };
    HRESULT hr = _GetThumbnails_orig(folderThis, 2, &dpa);
    if (FAILED(hr)) {
        DPA_DestroyCallback(hdpa, ReleaseShellItemDpaCallback, nullptr);
        return 0;
    }

    std::vector<ChildBitmap> candidates;
    int itemCount = DPA_GetPtrCount(hdpa);
    for (int i = 0; i < itemCount; ++i) {
        IShellItem* item = static_cast<IShellItem*>(DPA_GetPtr(hdpa, i));
        if (!item) {
            continue;
        }

        HBITMAP bitmap = nullptr;
        bool imageThumbnail = false;
        SIZE size = style == Win7 ? kWin7PreviewSize : kWin10PreviewSize;
        BitmapFlagOrder flagOrder = style == Win7 ? BitmapFlagOrder::Win7 : BitmapFlagOrder::Win10;

        if (SUCCEEDED(GetShellItemBitmap(item, size, kThumbnailFlags, kIconFlags, kCompatFlags, flagOrder, false, &bitmap, &imageThumbnail)) &&
            bitmap) {
            BITMAP bm = {};
            if (!GetObjectW(bitmap, sizeof(bm), &bm)) {
                DeleteObject(bitmap);
                continue;
            }

            candidates.push_back({bitmap, imageThumbnail, LooksLikePhotoBitmap(bitmap), bm.bmWidth * bm.bmHeight, i,});
        }
    }

    if (style == Win7) {
        std::sort(candidates.begin(), candidates.end(), [](const ChildBitmap& a, const ChildBitmap& b) {
            if (a.photoLike != b.photoLike) {
                return a.photoLike > b.photoLike;
            }
            if (a.area != b.area) {
                return a.area > b.area;
            }
            return a.originalIndex < b.originalIndex;
        });
    }

    int count = 0;
    for (ChildBitmap& candidate : candidates) {
        if (count < 2) {
            outBitmaps[count++] = candidate;
            candidate.bitmap = nullptr;
        }
        if (candidate.bitmap) {
            DeleteObject(candidate.bitmap);
        }
    }

    DPA_DestroyCallback(hdpa, ReleaseShellItemDpaCallback, nullptr);
    return count;
}

// ---------------- Windows 7 style code ----------------

static HRESULT DrawWin7PreviewOnSkewedPlane(HDC destDc, HBITMAP preview, bool secondary, SIZE target) {
    BITMAP bm = {};
    RETURN_LAST_ERROR_IF(!GetObjectW(preview, sizeof(bm), &bm));

    wil::unique_hdc plateDc(CreateCompatibleDC(destDc));
    wil::unique_hdc overlayDc(CreateCompatibleDC(destDc));
    RETURN_HR_IF_NULL(E_OUTOFMEMORY, plateDc);
    RETURN_HR_IF_NULL(E_OUTOFMEMORY, overlayDc);

    const SIZE plateSize = { bm.bmWidth + 8, bm.bmHeight + 8 };
    void* plateBitsRaw = nullptr;
    HBITMAP plateBitmap = nullptr;
    RETURN_IF_FAILED(Create32BitHBITMAP(destDc, plateSize, &plateBitsRaw, &plateBitmap));
    wil::unique_hbitmap plateGuard(plateBitmap);

    wil::unique_select_object plateSel(SelectObject(plateDc.get(), plateBitmap));
    ZeroMemory(plateBitsRaw, plateSize.cx * plateSize.cy * sizeof(RGBQUAD));

    wil::unique_hpen borderPen(CreatePen(PS_SOLID, 8, RGB(204, 204, 204)));
    wil::unique_select_object oldPen(SelectObject(plateDc.get(), borderPen.get()));
    Rectangle(plateDc.get(), 0, 0, plateSize.cx, plateSize.cy);
    SetAlpha(static_cast<RGBQUAD*>(plateBitsRaw), plateSize.cx, plateSize.cy, 255);

    wil::unique_select_object srcSel(SelectObject(overlayDc.get(), preview));
    BLENDFUNCTION blend = { AC_SRC_OVER, 0, 255, AC_SRC_ALPHA };
    if (!GdiAlphaBlend(plateDc.get(), 4, 4, bm.bmWidth, bm.bmHeight, overlayDc.get(), 0, 0, bm.bmWidth, bm.bmHeight, blend)) {
        StretchBlt(plateDc.get(), 4, 4, bm.bmWidth, bm.bmHeight, overlayDc.get(), 0, 0, bm.bmWidth, bm.bmHeight, SRCCOPY);
    }

    POINT points[3] = {};
    CopyMemory(points, secondary ? kWin7SkewInfo.secondary : kWin7SkewInfo.primary, sizeof(points));
    ScalePoints(points, kWin7SkewInfo.size, target);

    int offsetX = 0;
    int offsetBase = plateSize.cx + (secondary ? 0 : -50) - plateSize.cy;
    if (static_cast<float>(plateSize.cx) <= static_cast<float>(plateSize.cy) * 1.1f) {
        offsetX = MulDiv(offsetBase + 32, target.cx, kWin7SkewInfo.size.cx);
    } else {
        points[0].y = MulDiv(106, target.cx, kWin7SkewInfo.size.cx);
        points[1].y = MulDiv((secondary ? 140 : 116) + 70, target.cx, kWin7SkewInfo.size.cx);
        offsetX = MulDiv(static_cast<int>(static_cast<float>(offsetBase) * 0.8f), target.cx, kWin7SkewInfo.size.cx);
    }

    RETURN_LAST_ERROR_IF(!PlgBlt(destDc, points, plateDc.get(), offsetX, 0, plateSize.cx - offsetX, plateSize.cy, nullptr, 0, 0));

    if (secondary) {
        wil::unique_hmodule shell32(LoadLibraryExW(L"shell32.dll", nullptr, LOAD_LIBRARY_AS_IMAGE_RESOURCE | LOAD_LIBRARY_AS_DATAFILE));
        if (shell32) {
            wil::unique_hbitmap shadow(LoadBitmapW(shell32.get(), MAKEINTRESOURCEW(0x137)));
            if (shadow && GetObjectW(shadow.get(), sizeof(bm), &bm)) {
                wil::unique_select_object shadowSel(SelectObject(overlayDc.get(), shadow.get()));
                GdiAlphaBlend(destDc, points[1].x, points[1].y, bm.bmWidth, points[2].y - points[0].y, overlayDc.get(), 0, 0, bm.bmWidth, bm.bmHeight, blend);
            }
        }
    }

    return S_OK;
}

static HRESULT DrawWin7StyleOnWin10(IShellItem* item, HDC hdc, SIZE target, bool secondary) {
    HBITMAP rawBitmap = nullptr;
    bool imageThumbnail = false;
    RETURN_IF_FAILED(GetShellItemBitmap(item, kWin7PreviewSize, SIIGBF_RESIZETOFIT, kIconFlags, kCompatFlags, BitmapFlagOrder::Win7, false, &rawBitmap, &imageThumbnail));
    wil::unique_hbitmap bitmap(rawBitmap);
    return DrawWin7PreviewOnSkewedPlane(hdc, bitmap.get(), secondary, target);
}

static HRESULT ComposeWin7StyleFolderThumbnail(void* extractThis, HBITMAP* outBitmap) {
    *outBitmap = nullptr;
    void* folderThis = static_cast<BYTE*>(extractThis) - 0x48;

    ChildBitmap children[2];
    int previewCount = GetFolderChildBitmaps(folderThis, Win7, children);
    wil::unique_hbitmap preview0(children[0].bitmap);
    wil::unique_hbitmap preview1(children[1].bitmap);

    if (previewCount == 0) {
        return Extract_orig(extractThis, outBitmap);
    }

    ScopedScreenDC screenDc;
    RETURN_LAST_ERROR_IF_NULL(screenDc.get());

    wil::unique_hdc fullDc(CreateCompatibleDC(screenDc.get()));
    RETURN_HR_IF_NULL(E_OUTOFMEMORY, fullDc);

    void* fullBitsRaw = nullptr;
    HBITMAP fullBitmap = nullptr;
    RETURN_IF_FAILED(Create32BitHBITMAP(screenDc.get(), kSkewCanvasSize, &fullBitsRaw, &fullBitmap));
    wil::unique_hbitmap fullGuard(fullBitmap);
    wil::unique_select_object fullSel(SelectObject(fullDc.get(), fullBitmap));
    ZeroMemory(fullBitsRaw, kSkewCanvasSize.cx * kSkewCanvasSize.cy * sizeof(RGBQUAD));

    RETURN_IF_FAILED(DrawStockIconLayer(fullDc.get(), SIID_FOLDERBACK, kSkewCanvasSize, 0));
    RETURN_IF_FAILED(DrawWin7PreviewOnSkewedPlane(fullDc.get(), preview0.get(), false, kSkewCanvasSize));
    if (previewCount > 1 && preview1) {
        RETURN_IF_FAILED(DrawWin7PreviewOnSkewedPlane(fullDc.get(), preview1.get(), true, kSkewCanvasSize));
    }
    RETURN_IF_FAILED(DrawStockIconLayer(fullDc.get(), SIID_FOLDERFRONT, kSkewCanvasSize, 1));

    HBITMAP finalBitmap = nullptr;
    RETURN_IF_FAILED(ScaleBitmapUsingWIC(fullBitmap, kCanvasSize, &finalBitmap));
    *outBitmap = finalBitmap;
    return S_OK;
}

// ---------------- Windows 10 style code ----------------

static HRESULT DrawWin10PreviewOnSkewedPlane(HDC destDc, HBITMAP preview, bool secondary) {
    BITMAP bm = {};
    RETURN_LAST_ERROR_IF(!GetObjectW(preview, sizeof(bm), &bm));

    wil::unique_hdc srcDc(CreateCompatibleDC(destDc));
    wil::unique_hdc plateDc(CreateCompatibleDC(destDc));
    RETURN_HR_IF_NULL(E_OUTOFMEMORY, srcDc);
    RETURN_HR_IF_NULL(E_OUTOFMEMORY, plateDc);

    const SIZE plateSize = { 256, 256 };
    void* plateBitsRaw = nullptr;
    HBITMAP plateBitmap = nullptr;
    RETURN_IF_FAILED(Create32BitHBITMAP(destDc, plateSize, &plateBitsRaw, &plateBitmap));
    wil::unique_hbitmap plateGuard(plateBitmap);
    wil::unique_select_object plateSel(SelectObject(plateDc.get(), plateBitmap));
    ZeroMemory(plateBitsRaw, plateSize.cx * plateSize.cy * sizeof(RGBQUAD));

    wil::unique_hpen borderPen(CreatePen(PS_SOLID, 2, RGB(0xB7, 0xB7, 0xB7)));
    wil::unique_select_object oldPen(SelectObject(plateDc.get(), borderPen.get()));
    Rectangle(plateDc.get(), 0, 0, secondary ? plateSize.cx - 1 : plateSize.cx, plateSize.cy);

    wil::unique_hbrush fillBrush(CreateSolidBrush(RGB(0xF7, 0xF7, 0xF7)));
    RECT fillRect = { 1, 1, plateSize.cx - (secondary ? 2 : 1), plateSize.cy - 1 };
    FillRect(plateDc.get(), &fillRect, fillBrush.get());
    SetAlpha(static_cast<RGBQUAD*>(plateBitsRaw), plateSize.cx, plateSize.cy, 255);

    wil::unique_select_object srcSel(SelectObject(srcDc.get(), preview));
    BLENDFUNCTION blend = { AC_SRC_OVER, 0, 255, AC_SRC_ALPHA };
    int drawX = LocalMax(static_cast<int>((254 - bm.bmWidth) / 2), 1);
    int drawY = LocalMax(static_cast<int>((254 - bm.bmHeight) / 2), 1);
    int drawW = LocalMax(static_cast<int>(bm.bmWidth - (secondary ? 2 : 1)), 1);
    int sourceW = LocalMax(static_cast<int>(bm.bmWidth - 1), 1);

    if (!GdiAlphaBlend(plateDc.get(), drawX, drawY, drawW, bm.bmHeight, srcDc.get(), 0, 0, sourceW, bm.bmHeight, blend)) {
        StretchBlt(plateDc.get(), drawX, drawY, drawW, bm.bmHeight, srcDc.get(), 0, 0, sourceW, bm.bmHeight, SRCCOPY);
    }

    POINT points[3] = {};
    if (secondary) {
        points[0] = { 60, 38 };
        points[1] = { 161, 74 };
        points[2] = { 60, 213 };
    } else {
        points[0] = { 76, 38 };
        points[1] = { 207, 56 };
        points[2] = { 76, 216 };
    }

    RETURN_LAST_ERROR_IF(!PlgBlt(destDc, points, plateDc.get(), 0, 0, plateSize.cx, plateSize.cy, nullptr, 0, 0));

    if (secondary) {
        wil::unique_hmodule shell32(LoadLibraryExW(L"shell32.dll", nullptr, LOAD_LIBRARY_AS_IMAGE_RESOURCE | LOAD_LIBRARY_AS_DATAFILE));
        if (shell32) {
            wil::unique_hbitmap shadow(LoadBitmapW(shell32.get(), MAKEINTRESOURCEW(0x137)));
            BITMAP shadowInfo = {};
            if (shadow && GetObjectW(shadow.get(), sizeof(shadowInfo), &shadowInfo)) {
                wil::unique_hdc shadowDc(CreateCompatibleDC(destDc));
                if (shadowDc) {
                    wil::unique_select_object shadowSel(SelectObject(shadowDc.get(), shadow.get()));
                    int shadowHeight = points[2].y - points[0].y;
                    GdiAlphaBlend(destDc, points[1].x, points[1].y, shadowInfo.bmWidth, shadowHeight,
                                  shadowDc.get(), 0, 0, shadowInfo.bmWidth, shadowInfo.bmHeight, blend);
                }
            }
        }
    }

    return S_OK;
}

static HRESULT ComposeWin10StyleFolderThumbnail(void* extractThis, HBITMAP* outBitmap) {
    *outBitmap = nullptr;
    void* folderThis = static_cast<BYTE*>(extractThis) - 0x48;

    ChildBitmap children[2];
    int previewCount = GetFolderChildBitmaps(folderThis, Win10, children);
    wil::unique_hbitmap preview0(children[0].bitmap);
    wil::unique_hbitmap preview1(children[1].bitmap);

    if (previewCount == 0) {
        return Extract_orig(extractThis, outBitmap);
    }

    ScopedScreenDC screenDc;
    RETURN_LAST_ERROR_IF_NULL(screenDc.get());

    wil::unique_hdc destDc(CreateCompatibleDC(screenDc.get()));
    RETURN_HR_IF_NULL(E_OUTOFMEMORY, destDc);

    void* canvasBitsRaw = nullptr;
    HBITMAP canvasBitmap = nullptr;
    RETURN_IF_FAILED(Create32BitHBITMAP(screenDc.get(), kCanvasSize, &canvasBitsRaw, &canvasBitmap));
    wil::unique_hbitmap canvasGuard(canvasBitmap);
    wil::unique_select_object canvasSel(SelectObject(destDc.get(), canvasBitmap));
    ZeroMemory(canvasBitsRaw, kCanvasSize.cx * kCanvasSize.cy * sizeof(RGBQUAD));

    RETURN_IF_FAILED(DrawStockIconLayer(destDc.get(), SIID_FOLDERBACK, kCanvasSize, 1));
    RETURN_IF_FAILED(DrawWin10PreviewOnSkewedPlane(destDc.get(), preview0.get(), false));
    if (previewCount > 1 && preview1) {
        RETURN_IF_FAILED(DrawWin10PreviewOnSkewedPlane(destDc.get(), preview1.get(), true));
    }
    RETURN_IF_FAILED(DrawStockIconLayer(destDc.get(), SIID_FOLDERFRONT, kCanvasSize, 1));

    *outBitmap = canvasGuard.release();
    return S_OK;
}

// ---------------- Windows 11 style code ----------------

static void FillWin11GradientBackground(RGBQUAD* pixels, const SIZE& size, const SIZE& canvas, LONG cardX, LONG cardY) {
    float startX = canvas.cx * 0.5f - 104.0f;
    float startY = canvas.cy * 0.5f - 62.0f;
    float endX = canvas.cx * 0.5f + 62.0f;
    float endY = canvas.cy * 0.5f + 74.0f;
    float dx = endX - startX;
    float dy = endY - startY;
    float denom = dx * dx + dy * dy;

    for (int y = 0; y < size.cy; ++y) {
        for (int x = 0; x < size.cx; ++x) {
            float gx = static_cast<float>(cardX + x);
            float gy = static_cast<float>(cardY + y);
            float t = denom > 0.0f ? (((gx - startX) * dx + (gy - startY) * dy) / denom) : 0.0f;
            t = LocalMax(0.0f, LocalMin(1.0f, t));

            BYTE alpha = static_cast<BYTE>(153.0f + (102.0f - 153.0f) * t + 0.5f);
            pixels[y * size.cx + x] = { alpha, alpha, alpha, alpha };
        }
    }
}

static HRESULT DrawWin11LikeContentPlane(IShellItem* item, HDC destDc, SIZE target) {
    HBITMAP rawBitmap = nullptr;
    bool imageThumbnail = false;
    RETURN_IF_FAILED(GetShellItemBitmap(item, kWin11ContentSize, kThumbnailFlags, kIconFlags, kCompatFlags, BitmapFlagOrder::Win11, true, &rawBitmap, &imageThumbnail));
    wil::unique_hbitmap bitmap(rawBitmap);

    BITMAP bm = {};
    RETURN_LAST_ERROR_IF(!GetObjectW(bitmap.get(), sizeof(bm), &bm));

    wil::unique_hdc itemDc(CreateCompatibleDC(destDc));
    wil::unique_hdc cardDc(CreateCompatibleDC(destDc));
    RETURN_HR_IF_NULL(E_OUTOFMEMORY, itemDc);
    RETURN_HR_IF_NULL(E_OUTOFMEMORY, cardDc);

    SIZE cardSize = kWin11ContentSize;
    LONG cardX = (target.cx - cardSize.cx) / 2;
    LONG cardY = 66;
    RECT cardRect = { cardX, cardY, cardX + cardSize.cx, cardY + cardSize.cy };

    void* cardBitsRaw = nullptr;
    HBITMAP cardBitmap = nullptr;
    RETURN_IF_FAILED(Create32BitHBITMAP(destDc, cardSize, &cardBitsRaw, &cardBitmap));
    wil::unique_hbitmap cardGuard(cardBitmap);
    wil::unique_select_object cardSel(SelectObject(cardDc.get(), cardBitmap));
    ZeroMemory(cardBitsRaw, cardSize.cx * cardSize.cy * sizeof(RGBQUAD));

    RGBQUAD* pixels = static_cast<RGBQUAD*>(cardBitsRaw);
    FillWin11GradientBackground(pixels, cardSize, target, cardX, cardY);

    wil::unique_select_object itemSel(SelectObject(itemDc.get(), bitmap.get()));

    int srcW = bm.bmWidth;
    int srcH = bm.bmHeight;
    int drawX = 0;
    int drawY = 0;
    int drawW = cardSize.cx;
    int drawH = cardSize.cy;

    if (imageThumbnail) {
        float scale = LocalMax(static_cast<float>(cardSize.cx) / srcW, static_cast<float>(cardSize.cy) / srcH);
        drawW = static_cast<int>(srcW * scale + 0.5f);
        drawH = static_cast<int>(srcH * scale + 0.5f);
        drawX = (cardSize.cx - drawW) / 2;
        drawY = (cardSize.cy - drawH) / 2;
    } else {
        int iconMax = 128;
        float scale = LocalMin(static_cast<float>(iconMax) / srcW, static_cast<float>(iconMax) / srcH);
        scale = LocalMin(scale, 1.0f);
        drawW = static_cast<int>(srcW * scale + 0.5f);
        drawH = static_cast<int>(srcH * scale + 0.5f);
        drawX = (cardSize.cx - drawW) / 2;
        drawY = (cardSize.cy - drawH) / 2;
    }

    HRESULT drawHr = DrawBitmapWithWIC(bitmap.get(), pixels, cardSize, drawX, drawY, drawW, drawH);
    BLENDFUNCTION blend = { AC_SRC_OVER, 0, 255, AC_SRC_ALPHA };
    if (FAILED(drawHr)) {
        GdiAlphaBlend(cardDc.get(), drawX, drawY, drawW, drawH, itemDc.get(), 0, 0, srcW, srcH, blend);
    }

    int savedDc = SaveDC(destDc);
    wil::unique_hrgn roundedClip(CreateRoundRectRgn(cardRect.left, cardRect.top, cardRect.right, cardRect.bottom, 12, 12));
    RETURN_HR_IF_NULL(E_OUTOFMEMORY, roundedClip);
    SelectClipRgn(destDc, roundedClip.get());
    GdiAlphaBlend(destDc, cardRect.left, cardRect.top, cardSize.cx, cardSize.cy, cardDc.get(), 0, 0, cardSize.cx, cardSize.cy, blend);
    if (savedDc) {
        RestoreDC(destDc, savedDc);
    }

    return S_OK;
}

// ---------------- Hook dispatch code ----------------

static HRESULT __fastcall Extract_hook(void* pThis, HBITMAP* bitmap) {
    if (g_targetStyle == g_hostStyle) {
        return Extract_orig(pThis, bitmap);
    }

    HRESULT hr = E_FAIL;
    if (g_targetStyle == Win7) {
        hr = ComposeWin7StyleFolderThumbnail(pThis, bitmap);
    } else if (g_targetStyle == Win10) {
        hr = ComposeWin10StyleFolderThumbnail(pThis, bitmap);
    }

    if (SUCCEEDED(hr) && bitmap && *bitmap) {
        return hr;
    }

    return Extract_orig(pThis, bitmap);
}

static HRESULT __fastcall _SkewThumbnail_hook(void* self, UINT index, IShellItem* item, HDC hdc, SIZE target) {
    if (g_targetStyle == g_hostStyle) {
        return _SkewThumbnail_orig ? _SkewThumbnail_orig(self, index, item, hdc, target) : E_FAIL;
    }

    if (g_targetStyle == Win7) {
        return DrawWin7StyleOnWin10(item, hdc, target, index != 0);
    }

    if (g_targetStyle == Win11) {
        if (index > 0) {
            return S_OK;
        }

        g_drawWin10FrontShellForCurrentThumbnail = false;
        HRESULT hr = DrawWin11LikeContentPlane(item, hdc, target);
        if (SUCCEEDED(hr)) {
            g_drawWin10FrontShellForCurrentThumbnail = true;
            return hr;
        }

        return _SkewThumbnail_orig ? _SkewThumbnail_orig(self, index, item, hdc, target) : hr;
    }

    return _SkewThumbnail_orig ? _SkewThumbnail_orig(self, index, item, hdc, target) : E_FAIL;
}

static int AdjustWin7FolderShellFlags(int stockIconId, int flags) {
    constexpr int kWin7StuffedFolderBackShell = 0x4B;
    if (g_targetStyle == Win7 && stockIconId == kWin7StuffedFolderBackShell && flags == 1) {
        return 0;
    }
    return flags;
}

static HRESULT __fastcall s_DrawIcon_hook(int stockIconId, HDC hdc, SIZE target, int flags) {
    if (g_targetStyle == g_hostStyle) {
        return s_DrawIcon_orig ? s_DrawIcon_orig(stockIconId, hdc, target, flags) : E_FAIL;
    }

    constexpr int kWin10StuffedFolderFrontShell = 0x4C;

    if (g_targetStyle == Win11 && stockIconId == kWin10StuffedFolderFrontShell && !g_drawWin10FrontShellForCurrentThumbnail) {
        return S_OK;
    }

    HRESULT hr = s_DrawIcon_orig ?
        s_DrawIcon_orig(stockIconId, hdc, target, AdjustWin7FolderShellFlags(stockIconId, flags)) :
        E_FAIL;

    if (g_targetStyle == Win11 && stockIconId == kWin10StuffedFolderFrontShell) {
        g_drawWin10FrontShellForCurrentThumbnail = false;
    }

    return hr;
}

// windows.storage.dll
static const WindhawkUtils::SYMBOL_HOOK storagehook10[] = {
    {
        { L"private: long __cdecl CFolderThumbnail::_SkewThumbnail(unsigned int,struct IShellItem *,struct HDC__ *,struct tagSIZE)" },
        &_SkewThumbnail_orig,
        _SkewThumbnail_hook,
        false,
    },
    {
        { L"private: static long __cdecl CFolderThumbnail::s_DrawIcon(enum SHSTOCKICONID,struct HDC__ *,struct tagSIZE,int)" },
        &s_DrawIcon_orig,
        s_DrawIcon_hook,
        false,
    },
};

// windows.storage.dll
static const WindhawkUtils::SYMBOL_HOOK storagehook11[] = {
    {
        { L"public: virtual long __cdecl CFolderThumbnail::Extract(struct HBITMAP__ * *)" },
        &Extract_orig,
        Extract_hook,
        false,
    },
    {
        { L"private: long __cdecl CFolderThumbnail::_GetThumbnails(unsigned char,class CDPA<struct IShellItem,class CTContainer_PolicyUnOwned<struct IShellItem> > &)" },
        &_GetThumbnails_orig,
        nullptr,
        false,
    },
};

static DWORD GetWinBuild() {
    DWORD WinBuild;
    ((void (WINAPI*)(DWORD*, DWORD*, DWORD*))GetProcAddress(GetModuleHandle(L"ntdll.dll"), "RtlGetNtVersionNumbers"))(NULL, NULL, &WinBuild);
    WinBuild &= ~0xF0000000;
    return WinBuild;
}

static void LoadSettings() {
    PCWSTR setting = Wh_GetStringSetting(L"thumbnailStyle");
    g_hostStyle = GetWinBuild() > 20348 ? Win11 : Win10;

    if (_wcsicmp(setting, L"win7") == 0) {
        g_targetStyle = Win7;
    } else if (_wcsicmp(setting, L"win10") == 0) {
        g_targetStyle = Win10;
    } else if (_wcsicmp(setting, L"win11") == 0) {
        g_targetStyle = Win11;
    }
    Wh_Log(L"Target style: %s", setting);
    Wh_FreeStringSetting(setting);
}

BOOL Wh_ModInit() {
    DWORD build = GetWinBuild();
    Wh_Log(L"Windows build number: %lu", build);
    LoadSettings();

    HMODULE storage = GetModuleHandleW(L"windows.storage.dll");
    if (!storage) {
        Wh_Log(L"Failed to load windows.storage.dll");
        return FALSE;
    }
    if(build <= 20348){
        if (!WindhawkUtils::HookSymbols(storage, storagehook10, ARRAYSIZE(storagehook10))){
            Wh_Log(L"Failed to hook symbols");
            return FALSE;
        }
    } else {
        if (!WindhawkUtils::HookSymbols(storage, storagehook11, ARRAYSIZE(storagehook11))){
            Wh_Log(L"Failed to hook symbols");
            return FALSE;
        }
    }
    Wh_Log(L"Init");
    return TRUE;
}

void Wh_ModSettingsChanged() {
    Wh_Log(L"Settings changed. Please clean the thumbnail cache to see the change.");
    LoadSettings();
}
